#!/bin/sh
set -e

PARAM=$1
if [ $# -eq 0  ]; then
	PARAM="."
fi	
shift
command="find -type d \\( -name .git -o -name .svn \\) -prune -o -iname \"*${PARAM}*\" -print"
for arg in "$@"; do
	command="${command} | grep -i \"${arg}\"";
done;
eval $command
