#!/bin/bash
set -e

last_arg="${!#}"

PARAM=$1
if [ $# -eq 0  ]; then
	PARAM="."
fi	
shift
command="find -type d \\( -name .git -o -name .svn \\) -prune -o -type f -name \"*.pyc\" -prune -o -iname \"*${PARAM}*\" -print"
for arg in "$@"; do
	if [ $arg = '-e' ];
	then
		continue 
	fi
	command="${command} | grep -i \"${arg}\"";
done;
if  [ $last_arg = '-e' ];
then
	command="vim \$(${command})"
fi
eval $command
